version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chatuser
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
