version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - ${DOCKER_DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
